# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: github-action-test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  project-a-build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./project-a
    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'project-a/package-lock.json'
      - run: npm ci
      - name: lint 적용
        run: npm run lint
      - name: build
        run: npm run build
      - name: 테스트
        run: npm run test
  project-b-build:
    runs-on: ubuntu-latest

    env:
      working-directory: ./project-b

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path:  'project-b/package-lock.json'
      - run: npm ci
      - name: prisma client 생성
        run: npx prisma generate
      - name: lint 적용
        run: npm run lint
      - name: build
        run: npm run build
      - name: 테스트
        run: npm run test